For-loop to Map function
Creekside-Robotics/Vision-Processing-Code pull request #11
Opened 2022-11-24 16:18 UTC by josephhadad05

2022-11-24 16:24 UTC, josephhadad05 commented
@paulelliott 
Responding to [this](https://github.com/Creekside-Robotics/Vision-Processing-Code/pull/5#discussion_r1031474132) comment.

I had to define the function from within the `from_apriltags` method since the `map()` function only allowed one parameter for the function and I needed access to `cls` and `camera`.

2022-11-24 16:51 UTC, paulelliott commented
You're on the right track with this. In general I would discourage declaring functions within other functions though. Also, the `extractPostFromDetection` function has quite a bit going on. That's a clue that it should maybe be its own class. If you went that route you could do something like this:

```
ReferencePointPost(detection).cls()
```

Inside that class I would store the `detection` in the initializer then have functions to generate all those individual data points you're storing as variables throughout this function.

2022-11-24 20:58 UTC, paulelliott commented
This is looking really good! There are some more refactoring opportunities in there to take advantage of OO programming, like extracting methods for some of the calculated values in that big function. When you're working inside an object, any time you're storing a variable that's a clue it should probably be a method instead. You can work on that in this PR or save that for another time. Up to you.

2022-11-25 02:42 UTC, josephhadad05 commented
Thanks for the suggestions! Most of the major variables declarations and statements have been extracted to individual methods.

2022-11-25 16:38 UTC, Catalyst4222 requested changes

2022-11-25 16:38 UTC, Catalyst4222 commented on vision_processing/vision/reference_point.py
> +    def cartesianToPolarTranslation(self, x: float, y: float, z: float) -> list:
Since self isn't referenced in this method, why not make it a [staticmethod](https://docs.python.org/3/library/functions.html#staticmethod)?

2022-11-25 16:38 UTC, Catalyst4222 commented on vision_processing/vision/reference_point.py
> +        return GameField().reference_points.get(self.detection.tag_id)
Because `reference_points` is a class attribute of `GameField`, there's no need to instantiate it

2022-11-26 11:55 UTC, paulelliott approved these changes
This looks great! Well done!

2022-11-27 03:05 UTC, Catalyst4222 approved these changes

2022-11-27 03:06 UTC, merged